# Generated by Django 5.1 on 2024-12-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_brand_category_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='email',
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
