# Generated by Django 5.1 on 2024-12-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_userdetails_userdetail_remove_brand_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
