# Generated by Django 5.1 on 2024-12-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_brand_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
